[build]
  command = "npm run build"
  publish = "dist"

# Optional: Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-XSS-Protection = "1; mode=block"

